var dir_d1f80ff82539b6697abb4a4794b81257 =
[
    [ "basic_type.hpp", "basic__type_8hpp.html", "basic__type_8hpp" ],
    [ "contract.hpp", "contract_8hpp.html", "contract_8hpp" ],
    [ "core.hpp", "core_8hpp.html", "core_8hpp" ],
    [ "edge.hpp", "edge_8hpp.html", "edge_8hpp" ],
    [ "edge_miscellaneous.hpp", "edge__miscellaneous_8hpp.html", "edge__miscellaneous_8hpp" ],
    [ "edge_operator.hpp", "edge__operator_8hpp.html", "edge__operator_8hpp" ],
    [ "get_item.hpp", "get__item_8hpp.html", "get__item_8hpp" ],
    [ "implement.hpp", "implement_8hpp.html", "implement_8hpp" ],
    [ "io.hpp", "io_8hpp.html", "io_8hpp" ],
    [ "mpi.hpp", "mpi_8hpp.html", "mpi_8hpp" ],
    [ "name.hpp", "name_8hpp.html", "name_8hpp" ],
    [ "qr.hpp", "qr_8hpp.html", "qr_8hpp" ],
    [ "scalar.hpp", "scalar_8hpp.html", "scalar_8hpp" ],
    [ "shrink_and_expand.hpp", "shrink__and__expand_8hpp.html", "shrink__and__expand_8hpp" ],
    [ "svd.hpp", "svd_8hpp.html", "svd_8hpp" ],
    [ "symmetry.hpp", "symmetry_8hpp.html", "symmetry_8hpp" ],
    [ "TAT.hpp", "TAT_8hpp.html", "TAT_8hpp" ],
    [ "tensor.hpp", "tensor_8hpp.html", "tensor_8hpp" ],
    [ "tensor_miscellaneous.hpp", "tensor__miscellaneous_8hpp.html", "tensor__miscellaneous_8hpp" ],
    [ "timer.hpp", "timer_8hpp.html", "timer_8hpp" ],
    [ "trace.hpp", "trace_8hpp.html", "trace_8hpp" ],
    [ "transpose.hpp", "transpose_8hpp.html", "transpose_8hpp" ]
];